sudo: required
language: generic
services:
  - docker
before_install:
  - echo "start creating an image with dockerfile.dev"
  - docker build -t seungrihan/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true seungrihan/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test Success"